name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Initialize git user
        run: git init&& git config user.name "Unique" && git config user.email "uikit@unique.network"
      - name: Install project dependencies
        run: npm install
      - name: Extract version
        shell: bash
        id: version
        run: |
          echo "##[set-output name=version;]${GITHUB_REF#refs/*/v}"
      - name: NPM Build
        shell: bash
        run: |
          npm ci
          npm run build:sdk

      - name: NPM Publish
        working-directory: ./dist/packages/sdk
        shell: bash
        run: |
          npm version ${{ steps.version.outputs.version }}
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> .npmrc
          npm publish
